# WallFetch Configuration File
# Copy this file to ~/.config/wallfetch/config.yaml and customize as needed

# Default settings
default_source: wallhaven
download_dir: ~/Pictures/Wallpapers
max_concurrent: 5

# API Keys
api_keys:
  wallhaven: "your_wallhaven_api_key_here"

# Default fetch options for each source
defaults:
  wallhaven:
    categories: "anime,nature"
    resolution: "1920x1080"
    sort: "toplist"
    limit: 10
    # Aspect ratio filtering (great for ultrawide screens)
    aspect_ratios: ["16x9", "21x9", "32x9"]
    # Resolution requirements
    min_width: 1920
    min_height: 1080
    # max_width: 7680   # uncomment to set maximum width
    # max_height: 2160  # uncomment to set maximum height
    # Only allow landscape images (no portrait/phone wallpapers)
    only_landscape: true

# Database settings
database:
  path: "~/.local/share/wallfetch/wallpapers.db"
  auto_vacuum: true 